### ISSUE TITLE
How about use zap/log to instead the log import?

### ISSUE THREAD

**Issue by jyz0309** [vesoft-inc/nebula-go#102]
Just as the title said, maybe we can use zap to instead the go log import ? 
According to https://github.com/rs/logbench result, it shows that zap have good performance in logging.

**Comment by Aiee** [comment]
Hello,

Choosing a logger to use as the default client log may cause duplicated logs when users use a different logger. Since we don't know what loggers our users are using, we decided to create a logger interface that allows the user to implement the method in the interface with their preference of logger choice.

**Comment by jyz0309** [comment]
ok, thank~ 
BTW, I am interested in this project. But I have not found an issue that suitable to me, can you recommend an issue for me? @Aiee

**Comment by wey-gu** [comment]
> ok, thank~
> BTW, I am interested in this project. But I have not found an issue that suitable to me, can you recommend an issue for me? @Aiee

Dear @jyz0309,

We are reviewing everything to provide a better entry/labeled issues/content or guides for kind and new contributors like you, I feel sorry for not doing a great job, we will back to you (hopefullly)soon on this :-)

**Comment by wey-gu** [comment]
@jyz0309 BTW.

before we have more issues labeled, could you check https://summer.iscas.ac.cn/#/org/projectlist?lang=en and search `nebula` to see if any of the nebula projects are interesting to you to start from?
