### ISSUE TITLE
session pool error 'write: broken pipe' 

### ISSUE THREAD

**Issue by zwkno1** [vesoft-inc/nebula-go#235]
There is a lot of errors of 'write: broken pipe'  when the first time invoke SessionPool.Execute after  a long idle time.

nebula-go version: v3.3.0

**Comment by Aiee** [comment]
Is the nebula service still alive?

**Comment by zwkno1** [comment]
> Is the nebula service still alive?

yes.  After a lot of errors i can invoke this method normally。

**Comment by lllfx** [comment]
i got the same problem

**Comment by violin0622** [comment]
I've met same error. I found that when there'a long idle time(8 hours by default in config file), TCP connection may be recycled. 

Then client try to write a request to that connection after that, causing the EPIPE error.

**Comment by Dong148** [comment]
is this why cleaner doesn't work? 
https://github.com/vesoft-inc/nebula-go/blob/fae48de712b670cf0ec06c77e7ad85569dbe8207/session_pool.go#L445
means when conf idle time, cleaner will auto clean dead conn, but
https://github.com/vesoft-inc/nebula-go/blob/fae48de712b670cf0ec06c77e7ad85569dbe8207/session_pool.go#L501
means If all sessions eventually expire, they may not be cleaned up because the number of sessions  in pool did not exceed minSize

**Comment by HarrisChu** [comment]
after this https://github.com/vesoft-inc/nebula-go/pull/279, the issue should be not existed.

when execute with error `write: broken pipe`, it would create a new session, and return the valid session into pool.
