### ISSUE TITLE
怎么获取全部点和边的方法呢

### ISSUE THREAD

**Issue by light9009** [vesoft-inc/nebula-go#66]
如何查询全部的点和边以及他们的属性

**Comment by Aiee** [comment]
Hello, since this is not a client-oriented question, please post your question in the forum: https://discuss.nebula-graph.com.cn/

After fetching the vertices you need, check the `// Extract data from the resultSet` part in https://github.com/vesoft-inc/nebula-go/blob/master/gorountines_example/graph_client_goroutines_example.go for how to extract values from the query response.
